version: '3.9'
services:
  playa:
    build: .
    restart: on-failure
      #stdin_open: true # docker run -i
      #tty: true        # docker run -t
      #    entrypoint: /bin/sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


